# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    from_currency = None
    input_amount = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:#22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 380, 270))
        self.frame.setStyleSheet("background-color:   #5d8aa8;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"font-size: 18")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 241, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("exchanging.png"))
        self.label_2.setObjectName("label_2")
        self.to_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.to_currency.setGeometry(QtCore.QRect(50, 420, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.to_currency.setFont(font)
        self.to_currency.setStyleSheet("background-color: #22222e;\n"
"border-width: bold;\n"
"border: 2px solid #5d8aa8;;\n"
"border-radius: 25px;\n"
"color: white;")
        self.to_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.to_currency.setObjectName("to_currency")
        self.output_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(50, 490, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.output_amount.setFont(font)
        self.output_amount.setStyleSheet("background-color: #22222e;\n"
"border-width: bold;\n"
"border: 2px solid #5d8aa8;;\n"
"border-radius: 25px;\n"
"color: white;")
        self.output_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.output_amount.setObjectName("output_amount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 560, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: #5d8aa8;\n"
"border-radius: 20;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #fa4244;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.from_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.from_currency.setGeometry(QtCore.QRect(50, 350, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.from_currency.setFont(font)
        self.from_currency.setStyleSheet("background-color: #22222e;\n"
"border-width: bold;\n"
"border: 2px solid #5d8aa8;;\n"
"border-radius: 25px;\n"
"color: white;")
        self.from_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.from_currency.setObjectName("from_currency")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(50, 280, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.input_amount.setFont(font)
        self.input_amount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #5d8aa8;\n"
"border-radius: 25;\n"
"color: white;")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "КОНВЕРТЕР ВАЛЮТ"))
        self.pushButton.setText(_translate("MainWindow", "Конвертация"))
